Repository palantir/palantir-java-format, pull requests merged in 2019-11, with the labels that each got.

#70 Limit the max width of method chain dots
  changelog/@unreleased/pr-70.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/OpenOp.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Break.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Doc.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/DocBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/LevelDelimitedFlatValueDocVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Space.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Tok.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Token.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B21954779.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B32114928.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B35644813.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/I365.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/M.output
Labels: autorelease, merge when ready

#71 Fix: Limit dotted chains for expressions starting with complex expression
  changelog/@unreleased/pr-71.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B21031147.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B22488373.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/M.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-long-method-chain.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-long-method-chain.output
Labels: autorelease, merge when ready

#72 Move input metadata collection out of Output
  palantir-java-format/src/main/java/com/palantir/javaformat/OpsBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/Output.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/InputMetadata.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/InputMetadataBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInput.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaOutput.java
Labels: merge when ready, no changelog

#77 Minor internal renames
  palantir-java-format/src/main/java/com/palantir/javaformat/OpsBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Comment.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/CountWidthUntilBreakVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Doc.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/DocBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/DocVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/HasUniqueId.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/LevelDelimitedFlatValueDocVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/NonBreakingSpace.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/StartsWithBreakVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/State.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
Labels: merge when ready, no changelog

#51 Fix: Correctly support Intellij 193+
  build.gradle
  changelog/@unreleased/pr-51.v2.yml
  idea-plugin/build.gradle
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/CodeStyleManagerDecorator.java
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/GoogleJavaFormatInstaller.java
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/PalantirCodeStyleManager.java
  idea-plugin/src/main/resources/META-INF/plugin.xml
Labels: merge when ready

#80 Fix: reformat on commit uses PJF
  changelog/@unreleased/pr-80.v2.yml
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/PalantirCodeStyleManager.java
Labels: merge when ready

#73 HTML debugging view
  .gitignore
  debugger/.gitignore
  debugger/README.md
  debugger/package.json
  debugger/public/index.html
  debugger/src/App.css
  debugger/src/App.test.tsx
  debugger/src/App.tsx
  debugger/src/index.css
  debugger/src/index.tsx
  debugger/src/react-app-env.d.ts
  debugger/src/vendor.d.ts
  debugger/tsconfig.json
  debugger/yarn.lock
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/BreakBehaviour.java
  palantir-java-format/src/main/java/com/palantir/javaformat/Indent.java
  palantir-java-format/src/main/java/com/palantir/javaformat/OpenOp.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Break.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Comment.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Doc.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/HasUniqueId.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/JsonDocVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/NonBreakingSpace.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/NoopSink.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Obs.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/State.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Token.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/DebugRenderer.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JsonSink.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FormatterIntegrationTest.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-conjure-java-runtime-1285-1.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-conjure-java-runtime-1285-1.output
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#85 Fix: don't inline level prefix if breaks occurred inside
  changelog/@unreleased/pr-85.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-conjure-java-runtime-1285-1.output
Labels: autorelease, merge when ready

#88 Split debugger into files
  debugger/src/App.tsx
  debugger/src/Data.ts
  debugger/src/Doc.ts
  debugger/src/InlineDoc.tsx
  debugger/src/Ops.tsx
  debugger/src/TreeAndDoc.tsx
  debugger/src/TreeDoc.tsx
  debugger/src/common.tsx
Labels: merge when ready, no changelog
