Repository palantir/palantir-java-format, pull requests merged in 2019-10, with the labels that each got.

#41 FormatDiffCli improvements
  build.gradle
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/java/FormatDiff.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FormatDiffCliTest.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FormatDiffTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#43 Minimal README with some examples
  README.md
Labels: merge when ready, no changelog

#44 Improvement: better inlining of method reference
  changelog/@unreleased/pr-44.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-gcv-1.output
Labels: autorelease, merge when ready

#45 Fix: NON-NLS comments move before `+` in string concatenations
  changelog/@unreleased/pr-45.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/OpsBuilder.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/NON-NLS.output
Labels: autorelease, merge when ready

#47 Break: rename api->spi, remove JavaFormatterOptions and expose new method
  changelog/@unreleased/pr-47.v2.yml
  idea-plugin/build.gradle
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/PalantirCodeStyleManager.java
  palantir-java-format-api/src/main/java/com/palantir/javaformat/java/FormatterService.java
  palantir-java-format-spi/build.gradle
  palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/FormatterDiagnostic.java
  palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/FormatterException.java
  palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/FormatterService.java
  palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/JavaFormatterOptions.java
  palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/Replacement.java
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/java/FormatterServiceImpl.java
  settings.gradle
Labels: merge when ready

#48 Standalone gradle plugins
  build.gradle
  changelog/@unreleased/pr-48.v2.yml
  gradle-palantir-java-format/build.gradle
  gradle-palantir-java-format/src/main/groovy/com/palantir/javaformat/gradle/ConfigureExternalDependenciesXml.java
  gradle-palantir-java-format/src/main/groovy/com/palantir/javaformat/gradle/ConfigureJavaFormatterXml.groovy
  gradle-palantir-java-format/src/main/groovy/com/palantir/javaformat/gradle/ConfigurePalantirJavaFormatXml.java
  gradle-palantir-java-format/src/main/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatIdeaPlugin.java
  gradle-palantir-java-format/src/main/groovy/com/palantir/javaformat/gradle/UpdateIntellijXmlTask.java
  gradle-palantir-java-format/src/main/java/com/palantir/javaformat/gradle/FormatDiff.java
  gradle-palantir-java-format/src/main/java/com/palantir/javaformat/gradle/JavaFormatExtension.java
  gradle-palantir-java-format/src/main/java/com/palantir/javaformat/gradle/LineOffsetIterator.java
  gradle-palantir-java-format/src/main/java/com/palantir/javaformat/gradle/PalantirJavaFormatPlugin.java
  gradle-palantir-java-format/src/main/java/com/palantir/javaformat/gradle/PalantirJavaFormatProviderPlugin.java
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/ConfigureJavaFormatterXmlTest.groovy
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/FormatDiffTest.java
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatIdeaPluginTest.groovy
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatPluginTest.groovy
  gradle-palantir-java-format/src/test/resources/com/palantir/javaformat/java/FormatDiffCliTest/example1.patch
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/Utils.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/FormatFileCallable.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaOutput.java
  palantir-java-format/src/test/java/com/palantir/javaformat/NewlinesTest.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/LineRangesToCharRangesTest.java
  settings.gradle
  versions.lock
Labels: autorelease, merge when ready

#49 Update sinceBuild, don't publish IDEA plugin unless clean tag
  idea-plugin/build.gradle
Labels: merge when ready, no changelog

#54 State is now immutable
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/BreakBehaviour.java
  palantir-java-format/src/main/java/com/palantir/javaformat/Indent.java
  palantir-java-format/src/main/java/com/palantir/javaformat/Input.java
  palantir-java-format/src/main/java/com/palantir/javaformat/LastLevelBreakability.java
  palantir-java-format/src/main/java/com/palantir/javaformat/OpenOp.java
  palantir-java-format/src/main/java/com/palantir/javaformat/OpsBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/Output.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Break.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/BreakTag.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/ClearBreaksVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/CountWidthUntilBreakVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Doc.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/DocBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/HasUniqueId.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/ImmutableSupplier.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/LevelDelimitedFlatValueDocVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Space.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/State.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Tok.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Token.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInput.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaOutput.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B24909927.output
  versions.lock
  versions.props
Labels: merge when ready, no changelog
