Repository palantir/palantir-java-format, pull requests merged in 2020-11, with the labels that each got.

#358 Update spotless to 5.7.0
  changelog/@unreleased/pr-358.v2.yml
  gradle-palantir-java-format/src/main/java/com/palantir/javaformat/gradle/PalantirJavaFormatSpotlessPlugin.java
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatSpotlessPluginTest.groovy
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#353 Delete pom.xml?
  pom.xml
Labels: merge when ready, no changelog

#365 Add support for java 14 language features
  .circleci/config.yml
  .circleci/template.sh
  build.gradle
  changelog/2.0.0-rc1/pr-365.v2.yml
  changelog/@unreleased/pr-365.v2.yml
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatSpotlessPluginTest.groovy
  gradle/javadoc.options
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/java/DimensionHelpers.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/FormatterExceptions.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/ImportOrderer.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInput.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavacTokens.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/ModifierOrderer.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/RemoveUnusedImports.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/StringWrapper.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Trees.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/java14/Java14InputAstVisitor.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/DiagnosticTest.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FileBasedTests.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FormatterIntegrationTest.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/MainTest.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/StringWrapperIntegrationTest.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/ExpressionSwitch.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/ExpressionSwitch.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/RSL.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/RSL.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/Records.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/Records.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/Var.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/Var.output
  versions.lock
  versions.props
Labels: merge when ready
