Repository palantir/palantir-java-format, pull requests merged in 2020-02, with the labels that each got.

#172 A few more tests
  build.gradle
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-1.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-1.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-2.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-2.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-3.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-3.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-4.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-4.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-5.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-5.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-6.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-6.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-7.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-7.output
Labels: merge when ready, no changelog

#171 Readme blurb about method call column limit
  README.md
Labels: merge when ready, no changelog

#169 Better lambda/assignment inlining logic
  changelog/@unreleased/pr-169.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/State.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B18479811.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B32114928.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-1.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-2.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-3.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-7.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-8.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-8.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-chains-lambdas.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-lambda-inlining-prefers-break.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-lambda-inlining-prefers-break.output
Labels: autorelease, merge when ready

#191 inline annotation args
  changelog/@unreleased/pr-191.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B20529113.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B65214682.output
Labels: merge when ready

#192 Respect user's existing splits in string concatenations
  changelog/@unreleased/pr-192.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/OpsBuilder.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/B21305044.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/S.output
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-10.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-10.output
Labels: autorelease, merge when ready

#193 Fix lineSpan
  changelog/@unreleased/pr-193.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-10.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-10.output
Labels: autorelease, merge when ready

#203 Fix crash when breaking up long comment after simple lambda body
  changelog/@unreleased/pr-203.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/Level.java
  palantir-java-format/src/main/java/com/palantir/javaformat/doc/State.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-11.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/palantir-11.output
Labels: autorelease, merge when ready
