Repository palantir/palantir-java-format, pull requests merged in 2022-03, with the labels that each got.

#675 Fix readme gradle plugin/intellij plugin split
  README.md
Labels: no changelog, merge when ready

#676 improvement: bump jackson to 2.13.2
  changelog/@unreleased/pr-676.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#671 Handle non-sealed modifier
  changelog/@unreleased/pr-671.v2.yml
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FileBasedTests.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/I696.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/I696.output
Labels: autorelease, merge when ready

#682 Upgrade jackson-databind to 2.13.2.1 (CVE-2020-36518)
  build.gradle
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready
