Repository palantir/palantir-java-format, pull requests merged in 2022-01, with the labels that each got.

#613 Run tests on Java 17
  .circleci/config.yml
  .circleci/template.sh
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatPluginTest.groovy
  gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatSpotlessPluginTest.groovy
  gradle.properties
  palantir-java-format/build.gradle
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/java14/Java14InputAstVisitor.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/MainTest.java
Labels: no changelog, merge when ready

#617 PJF plugin supports the new `PLUGIN_DIR/lib/*.jar` structure
  changelog/@unreleased/pr-617.v2.yml
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/FormatterProvider.java
Labels: autorelease, merge when ready

#619 Fix the intellij plugin when the bundled formatter is used
  changelog/@unreleased/pr-619.v2.yml
  idea-plugin/build.gradle
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/FormatterProvider.java
Labels: autorelease, merge when ready

#620 remove the filer for jdk17
  changelog/@unreleased/pr-620.v2.yml
  idea-plugin/build.gradle
Labels: autorelease, merge when ready

#622 Handle empty format response replacements
  changelog/@unreleased/pr-622.v2.yml
  palantir-java-format-jdk-bootstrap/src/main/java/com/palantir/javaformat/bootstrap/BootstrappingFormatterService.java
Labels: bug, autorelease, merge when ready

#636 Fix idea plugin failures due to slf4j references
  changelog/@unreleased/pr-636.v2.yml
  idea-plugin/build.gradle
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/PalantirCodeStyleManager.java
Labels: autorelease, merge when ready

#644 Handle empty implementation version
  changelog/@unreleased/pr-644.v2.yml
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/PalantirJavaFormatConfigurable.java
  idea-plugin/src/main/java/com/palantir/javaformat/intellij/PalantirJavaFormatSettings.java
Labels: autorelease, merge when ready
