Repository palantir/palantir-java-format, pull requests merged in 2023-09, with the labels that each got.

#921 Add option to format javadoc
  changelog/@unreleased/pr-921.v2.yml
  palantir-java-format-spi/src/main/java/com/palantir/javaformat/java/JavaFormatterOptions.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaCommentsHelper.java
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaFormatterInternalOptions.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/FormatterIntegrationTest.java
  palantir-java-format/src/test/java/com/palantir/javaformat/java/JavadocFormattingTest.java
Labels: autorelease

#924 Remove outdated docs
  README.md
Labels: no changelog

#926 Handle `final var` lambda variables
  palantir-java-format/src/main/java/com/palantir/javaformat/java/JavaInputAstVisitor.java
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/I959.input
  palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/I959.output
Labels: no changelog, autorelease, merge when ready
